import H1 from '../H1'
export { H1 }
import H2 from '../H2'
export { H2 }
import H3 from '../H3'
export { H3 }
import H4 from '../H4'
export { H4 }
import H5 from '../H5'
export { H5 }
import H6 from '../H6'
export { H6 }