import H1 from '../../primatives/H1'
export { H1 }
import H2 from '../../primatives/H2'
export { H2 }
import H3 from '../../primatives/H3'
export { H3 }
import H4 from '../../primatives/H4'
export { H4 }
import H5 from '../../primatives/H5'
export { H5 }
import H6 from '../../primatives/H6'
export { H6 }
